### ISSUE TITLE
IndexError upon usage

### ISSUE THREAD

**Issue by XxTHKxX** [acheong08/Bard#28]
Traceback:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 980, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/container/bot.py", line 422, in bard
    response = await loop.run_in_executor(ThreadPoolExecutor(), bardchatbot.ask, message)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/Bard.py", line 135, in ask
    chat_data = json.loads(resp.content.splitlines()[3])[0][2]
IndexError: list index out of range

1.0.2 was working fine, but all of a sudden the error started appearing, then I did an update to 1.0.3, it didn't help though, so uh, I am really not sure what is going on there

**Comment by acheong08** [comment]
Perhaps an expired conversation or session cookie. Try updating your secure session cookie and running again. Also check to make sure the length of the message isn't too long

**Comment by XxTHKxX** [comment]
I redid the cookie step again, doesn't seem to be it, and the length of the message is definitely not too long, it's only like the first text in the convo

**Comment by henryyang1993** [comment]
got the same issue in the latest 1.1.3 version even after pasting the new `__Secure-1PSID`
```
  File "/home/ec2-user/.local/lib/python3.11/site-packages/Bard.py", line 149, in ask
    chat_data = json.loads(resp.content.splitlines()[3])[0][2]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
