### ISSUE TITLE
Issue with the chat_data = json.loads(resp.content.splitlines()[3])[0][2]

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/Bard#53]
from os import environ
from Bard import Chatbot

token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
chatbot = Chatbot(token)

chatbot.ask("Hello, how are you?")

when i ran it it always gives this error
Traceback (most recent call last):                                                                                                      
  File "P:\New Model Traning\Bard Jarvis\bard_jarvis.py", line 7, in <module>                                                           
    chatbot.ask("Hello, how are you?")                                                                                                  
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\Bard.py", line 83, in ask                              
    return self.loop.run_until_complete(self.async_chatbot.ask(message))                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete             
    return future.result()                                                                                                              
           ^^^^^^^^^^^^^^^                                                                                                              
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\Bard.py", line 236, in ask                             
    chat_data = json.loads(resp.content.splitlines()[3])[0][2]                                                                          
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^                                                                                 
IndexError: list index out of range

**Comment by Meshwa428** [comment]
are you still making this or you are focused on edgeGPT

**Comment by acheong08** [comment]
I'm on vacation

**Comment by acheong08** [comment]
I'll look into it

**Comment by acheong08** [comment]
cant replicate

**Comment by Meshwa428** [comment]
No need 😅 I am a beginner and didn't knew that my cookie expired it changed in the browser, so ya now it works fine. Can add something that extracts the __P1SID from chrome and then adds it to the code

**Comment by acheong08** [comment]
Automating login would be a nightmare
