### ISSUE TITLE
Error with the example python code from the readme

### ISSUE THREAD

**Issue by DomiNike111** [acheong08/Bard#77]
The code:
from os import environ
from Bard import Chatbot

Secure_1PSID = <the token as a string>
Secure_1PSIDTS = <the token as a string>

chatbot = Chatbot(Secure_1PSID, Secure_1PSIDTS)

chatbot.ask("Hello, how are you?")

The error:
PS C:\Users\havas\Documents\vspy\revgooglebard> & C:/Users/havas/AppData/Local/Programs/Python/Python39/python.exe c:/Users/havas/Documents/vspy/revgooglebard/main.py
Traceback (most recent call last):
  File "c:\Users\me\revgooglebard\main.py", line 7, in <module>
    chatbot = Chatbot(Secure_1PSID, Secure_1PSIDTS)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\Bard.py", line 64, in __init__
    self.async_chatbot = self.loop.run_until_complete(
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\Bard.py", line 155, in create
    instance.SNlM0e = await instance.__get_snlm0e()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\Bard.py", line 230, in __get_snlm0e
    resp = await self.session.get(
TypeError: get() got an unexpected keyword argument 'follow_redirects'

**Comment by acheong08** [comment]
Upgrade your httpx version
